### ISSUE TITLE
The example page logs current state instead of next state

### ISSUE THREAD

**Issue by iki** [evgenyrodionov/redux-logger#147]
1. Open the example page https://theaqua.github.io/redux-logger/
2. Do any operation, and view the log.

_Expected:_ the next state logged to console equals to the state after the operation
_Current:_ the next state logged to console equals to the state **before** the operation, instead

**Comment by theaqua** [comment]
I see. It's interesting.

**Comment by toxickg** [comment]
I can't replicate this problem running the latest version of example locally. So, I suppose it's a bug that occurred in earlier versions.

We haven't updated the hosted example for [quite some time](https://github.com/theaqua/redux-logger/tree/gh-pages).

**Comment by toxickg** [comment]
We should update it and close this issue afterwards.

**Comment by alexis-thual** [comment]
Has there been any progress on this so far?

**Comment by stuartsimpson** [comment]
I am on version 3.0.6 of redux-logger and version 3.7.2 of redux and it still appears to exist.  I am also using redux-promise-middleware (v4.4.1) and redux-thunk (v2.2.0).  When i examine the state through the React plugin for Chrome the state is correct there.  the changed element is a nested array inside the Object.  Let me know if i can provide any additional information that may help.

**Comment by grushetsky** [comment]
Closing the issue as the example page is no longer available.
