### ISSUE TITLE
Looking for a new maintainer for redux-logger

### ISSUE THREAD

**Issue by evgenyrodionov** [evgenyrodionov/redux-logger#148]
Hi, guys!

I don't have enough time for redux-logger, but to be honest, redux-logger is very stable and have only 4 issues in roadmap:
* diff feature (#136)
* suspicious bug with example configuration (#147)
* better readme and code — it's a little bit messy right now
* tests?

If anyone wants to be a maintainer (one is enough) of redux-logger, send me a message at reduxlogger@theaqua.im, I'll give access to repository and npm package.

**Comment by cjke** [comment]
Just curious if this was still open-open?
