### ISSUE TITLE
stuck / crash on react-native if state is long

### ISSUE THREAD

**Issue by hitbear518** [evgenyrodionov/redux-logger#154]
I have a quite long state, and every time when redux-logger run, my app will stuck or even crash

**Comment by toxickg** [comment]
Are you sure that the problem can't be reproduced with smaller state? Did you try that?

What version of the package are you using?

**Comment by hitbear518** [comment]
I'm using redux-logger@2.6.1, react-native@0.25.1,  
when state is small, it's ok, but after fetching data and put it in redux store, state got pretty big and everytime redux-logger log, UI will freeze.
It will not stuck when the app is running on debug mode (Javascript run on chrome), but when run on iOS
 and Android, It will stuck / crash.

**Comment by grushetsky** [comment]
@hitbear518, closing this for now as no detailed information was provided. In case you stumble upon this problem again, please, post here.
