### ISSUE TITLE
Question: Anything holding back diff from release?

### ISSUE THREAD

**Issue by ReactiveRaven** [evgenyrodionov/redux-logger#159]
I was pretty excited to see the `diff` option in the README, but it looks like it only actually [dropped after the latest release](https://github.com/theaqua/redux-logger/compare/2.6.1...master) so it can't be installed with a sensible semver restriction through NPM - Is there anything holding back tagging a new release?

Thanks

**Comment by toxickg** [comment]
The diff feature is not yet ready, primarily because of an issue with array diffing. Unfortunately, there's no ETA right now on when it's going to be fixed.

You can find the corresponding discussion [here](https://github.com/theaqua/redux-logger/issues/136#issuecomment-220663008).
