### ISSUE TITLE
Log error when logger factory is passed directly to applyMiddleware.

### ISSUE THREAD

**Issue by sesm** [evgenyrodionov/redux-logger#160]
Currently, if user makes a mistake like this:
`import logger from 'redux-logger'`
`...`
`let store = createStore(reducers, applyMiddlware(logger));`
There will be no error messages in console and all actions will be silently discarded.
It would be nice to write an error message to console, when createLogger is used incorrectly like this.

**Comment by friktor** [comment]
👍+

**Comment by evgenyrodionov** [comment]
PR welcome
