### ISSUE TITLE
Release fresh version to npm

### ISSUE THREAD

**Issue by Strate** [evgenyrodionov/redux-logger#163]
Seems that npmjs registry contains outdated version of this package, without diff functionality. It would be nice if you release a fresh version, guys.

**Comment by evgenyrodionov** [comment]
Diff feature is not completed yet, it's buggy (fcomb/redux-diff-logger#1)

**Comment by sibelius** [comment]
I think the current version of diff is working fine, it is the same of redux-diff-logger

**Comment by johanneserber** [comment]
👍 please release! 😄

**Comment by cannoneyed** [comment]
@evgenyrodionov any more progress on this one?

**Comment by toxickg** [comment]
We'll try to make a release in the upcoming week.

**Comment by phanimahesh** [comment]
Please make a beta release if you don't consider this ready for a stable release.

**Comment by grushetsky** [comment]
The [new version](https://github.com/evgenyrodionov/redux-logger/releases/tag/2.7.0) has just been released! Thank you for your patience!
