### ISSUE TITLE
Assignment to read-only properties is not allowed in strict mode (IE11)

### ISSUE THREAD

**Issue by ldabiralai** [evgenyrodionov/redux-logger#164]
Seeing an issue when using redux-logger in IE11.

![image](https://cloud.githubusercontent.com/assets/1711610/16384718/fb009938-3c81-11e6-895e-3a743397939d.png)

I'm guessing this is probably an easy fix, but I don't see how `throw logEntry.error` is assigning anything.

Happy to submit a PR if you can give me some guidance!

**Comment by ldabiralai** [comment]
Okay, discovered it was actually an issue on my end.. oops!

**Comment by axelson** [comment]
@ldabiralai what was the issue on your end?
