### ISSUE TITLE
Use conventional-changelog to generate changelog

### ISSUE THREAD

**Issue by stevemao** [evgenyrodionov/redux-logger#167]
Since you are already using the angular style commit message, it's very easy to use [conventional-changelog](https://github.com/conventional-changelog) to automate your releases. There are a lot of options, we recommend [standard-version](https://github.com/conventional-changelog/standard-version). But you are using github releases, there is also [conventional-github-releaser](https://github.com/conventional-changelog/conventional-github-releaser).

**Comment by evgenyrodionov** [comment]
Looks good, thanks
