### ISSUE TITLE
Transform action title

### ISSUE THREAD

**Issue by megatolya** [evgenyrodionov/redux-logger#171]
Hi!

I want to transform my action title form this `action @ 13:39:42.835 movie/OPEN_MOVIE_GALLERY ` to something like this `action @ 13:39:42.835 movie/OPEN_MOVIE_GALLERY (fail)` "fail" is stored in action but not in `type` prop. Thus I want to provide a function that creates action title.

If you dont mind I can provide PR

**Comment by megatolya** [comment]
@evgenyrodionov ping :)

**Comment by evgenyrodionov** [comment]
Feel free to create pr

**Comment by megatolya** [comment]
Created #172

**Comment by megatolya** [comment]
Also found #165. At first i planned to do quiet same, but it is not comfortable to create my own "timestamp" variables and etc in my `titleFormatter`. I just want to control action title itself. Maybe both functions are needed but in my case #165 is overhead.

**Comment by megatolya** [comment]
@evgenyrodionov ping :)

**Comment by evgenyrodionov** [comment]
Merged #165
