### ISSUE TITLE
TypeError when `performance` is null, not undefined

### ISSUE THREAD

**Issue by sompylasar** [evgenyrodionov/redux-logger#173]
https://github.com/evgenyrodionov/redux-logger/blob/47e5980b989e82ebde94a7060b0b497f9aef3ceb/src/helpers.js#L8

```
// Use performance API if it's available in order to get better precision
export const timer = typeof performance !== `undefined` && typeof performance.now === `function` ? performance : Date;
```

typeof null is not 'undefined', so `performance.now` dereferencing fails.

**Comment by evgenyrodionov** [comment]
Which env do you use?

**Comment by sompylasar** [comment]
It's been 22 days... I use Chrome and Node (isomorphic), but I don't remember the details of this error now. Now I just see a piece of code that makes false assumptions, so it does not handle every possible case.

**Comment by evgenyrodionov** [comment]
Next check is 
```
typeof performance.now === `function`
```

and it can't fail, because obviously `null` is not a function

**Comment by sompylasar** [comment]
True, but "performance" itself is null, so "null.now" throws.

**Comment by evgenyrodionov** [comment]
Ah, I see, you're right.
