### ISSUE TITLE
Add support for selector update logging

### ISSUE THREAD

**Issue by simonayzman** [evgenyrodionov/redux-logger#175]
This tool provides excellent support for pre- and post-action redux state change information. It would be good to also see how [memo-ized selectors](https://github.com/reactjs/reselect) change based on the state updates.

**Comment by evgenyrodionov** [comment]
I never used `reselect` so feel free to send PR

**Comment by simonayzman** [comment]
I wouldn't really know how to get started on something like this, to be honest.

**Comment by evgenyrodionov** [comment]
I thought about this and came to the conclusion that this is not job of redux-logger.
