### ISSUE TITLE
Logging unreadable with Chrome dark theme

### ISSUE THREAD

**Issue by LPGhatguy** [evgenyrodionov/redux-logger#178]
Chrome has a built-in dark theme in recent versions. The messages outputted by `redux-logger` are black, which blends into the background!

![screen shot 2016-09-29 at 2 47 17 pm](https://cloud.githubusercontent.com/assets/654598/18971815/c0344dc4-8653-11e6-8128-eb1224570dcc.png)

**Comment by grushetsky** [comment]
It has been fixed in #176, but we didn't manage to release the new version yet.
