### ISSUE TITLE
Turn logging on/off programmatically at runtime

### ISSUE THREAD

**Issue by freeranger** [evgenyrodionov/redux-logger#189]
It would be really useful if we could turn logging off/on at will.
For example in a production environment if there is a problem, you could drop into the console window and turn on logging to inspect the redux logs.

**Comment by evgenyrodionov** [comment]
Use `predicate` option

**Comment by freeranger** [comment]
Great thanks, works perfectly

**Comment by blueberryfan** [comment]
@freeranger How did you achieve what you described? I'm thinking I could have a predicate function that looks for a certain variable that normally isn't defined, but that I can temporarily define in order to temporarily turn on logging. What did you do? Cheers.

**Comment by freeranger** [comment]
Sorry I have no access to that codebase anymore to job my memory but I believe it was something similar to what you describe

**Comment by blueberryfan** [comment]
@freeranger No problem. In case it's of interest, I ended up doing something like this:

const actions = [] // hardcode any actions you like to always log here, eg ['ACTION1','ACTION2']

export default createLogger({
  ...
  predicate: (getState, action) => includeAlways(action.type) || includeTemporarily(action.type)
})

const includeAlways = actionType => actions.includes(actionType)
const includeTemporarily = actionType =>
  window && window.MY_GLOBAL && window.MY_GLOBAL.log && window.MY_GLOBAL.log.enabled === true && isArr(window.MY_GLOBAL.log.actions) && window.MY_GLOBAL.log.actions.includes(actionType)

I can then add some actions to log by running something like this in the browser console:

MY_GLOBAL = { log: { enabled: true, actions: ['ACTION3', 'ACTION4'] } }

And turn them off by modifying the actions array, eg

MY_GLOBAL = { log: { enabled: false, actions: [] } }

Seems to do the job for now.

Cheers.
