### ISSUE TITLE
Symbol values for action.type breaks apps when the redux-logger enabled

### ISSUE THREAD

**Issue by appmux** [evgenyrodionov/redux-logger#195]
### Problem
The following code breaks apps when the redux-logger is simply enabled with a default configuration.

```
let action = {type: Symbol('RANDOM_ACTION_TYPE')}
```

This kind of stuff should work out of the box, because as a developer I don't expect any dependency I choose to use to break my existing code. Especially when it comes to logging.

Think about it: `console.log(Symbol())` - works no problem, I do not have to convert a symbol to a string myself or use any sort of recipe.

### Workaround
There is a "solution" offered by a recipe:

```
import createLogger from 'redux-logger';

const logger = createLogger({
  actionTransformer: (action) => ({
    ...action,
    type: String(action.type),
  })
});
```

### Real solution

The real solution is to forcefully convert ANY type of data to a string when logging.

**Comment by evgenyrodionov** [comment]
Fixed in [2.8.1](https://github.com/evgenyrodionov/redux-logger/releases/tag/2.8.1)
