### ISSUE TITLE
Cannot find module 'redux-logger'.

### ISSUE THREAD

**Issue by lucib** [evgenyrodionov/redux-logger#199]
Uncaught Error: Module build failed: Error: app.module.ts (42,26): Cannot find module 'redux-logger'.)

it looks like i can't get it work with Angular 2 and Typescript even with all the changes from https://github.com/Microsoft/TypeScript/issues/5565

code
import createLogger from 'redux-logger';
ngRedux.configureStore(rootReducer, {}, [createLogger()]);

did anyone encountered this ?

**Comment by grushetsky** [comment]
@lucib, I think that I stumbled upon this problem. Try importing using `require`, please. Does it work?

**Comment by lucib** [comment]
it worked, tx

const createLogger = require(`redux-logger`);
ngRedux.configureStore(rootReducer, {}, [createLogger({collapsed: 'true'})]);
