### ISSUE TITLE
Problem with module resolution

### ISSUE THREAD

**Issue by lexon0011** [evgenyrodionov/redux-logger#202]
I use the redux logger in my angular 2 app with the following statement:
`import   * as createLogger  from "redux-logger";`

Since I try to us AOT, this isn't possible because namespaces are not allowed. So I change it to the following statement:
`import   createLogger  from "redux-logger";`

Now AOT works, but in the development it doesn't work. I get the following error message:
`redux_logger_1.default is not a function`

If I remove the following line in the `redux-logger/dist/index.js` it works in both environments:
`module.exports = exports['default'];`

Whats the problem here. What is the prevert way to use redux-logger in an Angular2/Typescript project?

In the attachment you find my my tsconfig.js and system.js configuration

Thanks

[tsconfig_systemjs.zip](https://github.com/evgenyrodionov/redux-logger/files/773475/tsconfig_systemjs.zip)

**Comment by grushetsky** [comment]
@lexon0011, take a look at this solution: https://github.com/evgenyrodionov/redux-logger/issues/199#issuecomment-272559893. We'll work it out eventually.

**Comment by lexon0011** [comment]
@grushetsky I try it: 

- The approch works in development with systemJS 
- AOT compilation and rollup finished successfull
- But at runtime I get the following error:
`Module name "redux-logger" has not been loaded yet for context: _. Use require([])`

I think I need a way to import the module with the "import" statement instead of "require". But then I always get the above error.

**Comment by evgenyrodionov** [comment]
Continue discussion in #208
