### ISSUE TITLE
UTC format

### ISSUE THREAD

**Issue by esalter** [evgenyrodionov/redux-logger#206]
An option to show the timestamp in UTC format would be great.  Even better, a way to control the output format or even the library used would be awesome.  Perhaps the "timestamp" option could take either a boolean ("true" defaults to what it does now), or a function that would return the formatted timestamp.

**Comment by evgenyrodionov** [comment]
Hi, @esalter! Sorry for delay.

You can use `titleFormatter` option. For example,

```
import createLogger from 'redux-logger';

const logger = {
  titleFormatter: (action) => {
    const time = new Date().toISOString();

    return `${time} action ${action.type}`
  }
}
```

**Comment by esalter** [comment]
Sorry for the delay to your delay, email snafus ;)

That does exactly what I needed, thanks!
