### ISSUE TITLE
Issues on Explorer when DevToolbar is not open

### ISSUE THREAD

**Issue by silverHub** [evgenyrodionov/redux-logger#207]
First of all there is no documentation what methods are used on the console object, because of this it is hard to create a failsafe console object => in Explorer 11 there is no console when devTools is not open.
A typical error situation when we start with devTool open and close in one point of time -> JS errors during application usage

**Comment by evgenyrodionov** [comment]
Make object with no-op `log` and `group` functions and then pass to `options.logger`
