### ISSUE TITLE
[CommonJS] Future-proof way of passing the default logger

### ISSUE THREAD

**Issue by williamboman** [evgenyrodionov/redux-logger#211]
Hey, is it OK to regard whatever `createLogger()` (with no arguments) returns to be the same as the default logger? I'd prefer not to use `require('redux-logger').default` as it's a babel-specific ES module workaround.

**Comment by evgenyrodionov** [comment]
You can import default logger, if you're prefer CommonJS.
```javascript
const { logger } = require('redux-logger')
```

or, of course,
```javascript
const { createLogger } = require('redux-logger')

const logger = createLogger()
```

But we decided to drop support because it's not friendly with named exports. More information: https://github.com/evgenyrodionov/redux-logger/issues/210#issuecomment-288672170
