### ISSUE TITLE
How to remove file name from title?

### ISSUE THREAD

**Issue by demian85** [evgenyrodionov/redux-logger#214]
It's too long... and titleFormatter option does not seem to do anything, file name is hardcoded before the formatted string.
Note: I'm working with Electron.

![image](https://cloud.githubusercontent.com/assets/470630/24416783/4d0131fe-13bc-11e7-9fe1-4d3882c58211.png)

Thanks.

**Comment by evgenyrodionov** [comment]
It's Chrome feature of console.log, we don't pass file name.
