### ISSUE TITLE
Using titleFormatter breaks color formatting in Chrome

### ISSUE THREAD

**Issue by jdelman** [evgenyrodionov/redux-logger#215]
Using v2.10.2.

I have a `titleFormatter` method that adds a few strings to the title. Unfortunately now there is some CSS junk appended to every line of the log, like so:

`action @ 16:24:54.996 data/FETCH_COMPLETE (in 4.33 ms) color: inherit; color: gray; font-weight: lighter; color: gray; font-weight: lighter;`

Here is a screenshot of the behavior: 

![screenshot 2017-03-29 16 23 18](https://cloud.githubusercontent.com/assets/2815533/24475053/bc7556c4-149c-11e7-9df6-cd59aae1faff.png)

This happens even when using the example in the README: `action @ ${time} ${action.type} (in ${took.toFixed(2)} ms)`.

**Comment by evgenyrodionov** [comment]
Nah, yes, we have that bug, will fix tomorrow.

Or you can create PR, if you want (hint: pass colors only when defaultFormatter applied)
