### ISSUE TITLE
Readme maybe add  some detail about  redux-persist

### ISSUE THREAD

**Issue by phpsmarter** [evgenyrodionov/redux-logger#219]
`export default function configureStore(initialState) {
  return createStore(
    rootReducer,
    initialState,
    compose(
    applyMiddleware(logger),
    autoRehydrate()
    )
  );
}`

**Comment by evgenyrodionov** [comment]
For what?

**Comment by evgenyrodionov** [comment]
redux-logger is [middleware](http://redux.js.org/docs/advanced/Middleware.html), redux-persist is [store enhancer](http://redux.js.org/docs/Glossary.html#store-enhancer) and they are composed by [`compose`](http://redux.js.org/docs/api/compose.html) helper.

So if you familiar with redux, you'll setup both without any recipes or notices about third-party libraries.

**Comment by phpsmarter** [comment]
thanks a lot
