### ISSUE TITLE
Use rollup instead of webpack

### ISSUE THREAD

**Issue by thiamsantos** [evgenyrodionov/redux-logger#225]
Basically [rollup](http://rollupjs.org/) is better than [webpack](https://webpack.js.org/) to build libraries, the article: [Webpack and Rollup: the same but different](https://medium.com/webpack/webpack-and-rollup-the-same-but-different-a41ad427058c) explains why. So I'd like to send a PR to replace the present webpack build for one that uses rollup.

**Comment by evgenyrodionov** [comment]
Let's do it 💪

**Comment by thiamsantos** [comment]
The [current scripts](https://github.com/evgenyrodionov/redux-logger/blob/master/package.json#L6) make use of many funcionalities of bash. But the users of windows may not be able to run these scripts. I think that would be good to make the scripts cross-plataform. What's your opinion @evgenyrodionov?

**Comment by evgenyrodionov** [comment]
@thiamsantos why not

**Comment by thiamsantos** [comment]
:tada: I'll start right now.

**Comment by thiamsantos** [comment]
@evgenyrodionov I'm facing a huge problem here. Looks like [`deep-diff`](https://github.com/flitbit/diff) exports only an [umd version](https://github.com/flitbit/diff/blob/master/index.js) of the module and rollup doesn't work well with umd builds. So, what should I do? Send a PR to `deep-diff` to fix that? Give up of using rollup? Or do something else?

**Comment by evgenyrodionov** [comment]
PR for them is better, because project alive

**Comment by thiamsantos** [comment]
I opened and issue there flitbit/diff#92. Just waiting for response.

**Comment by thiamsantos** [comment]
@evgenyrodionov my pull request was merged flitbit/diff#93 . Now it's just wait for the release.

**Comment by evgenyrodionov** [comment]
@thiamsantos awesome!
