### ISSUE TITLE
How to use logger with non plain actions?

### ISSUE THREAD

**Issue by indapublic** [evgenyrodionov/redux-logger#226]
If I have plain action:

```
export const getAlbums = () => ({
  type: types.SET,
  payload: {}
})
```

, all is fine. But if I'm using redux-thunk as middleware:

```
export const getAlbums = () => (dispatch, getState) => {
  dispatch({
    type: types.SET,
    payload: {}
  })
}
```

, I see strange records in logger

<img width="412" alt="screen shot 2017-04-24 at 02 49 25" src="https://cloud.githubusercontent.com/assets/856260/25315476/a6c156b0-2898-11e7-9e6d-960c83c0fab5.png">

**Comment by evgenyrodionov** [comment]
> [Usage](https://github.com/evgenyrodionov/redux-logger#usage)
> Note: logger must be the last middleware in chain, otherwise it will log thunk and promise, not actual actions (#20).
