### ISSUE TITLE
3.0.2 is unable to be parsed

### ISSUE THREAD

**Issue by mcrawshaw** [evgenyrodionov/redux-logger#229]
```Module parse failed: ~/node_modules/redux-logger/src/index.js Unexpected token (26:4)```

@evgenyrodionov

**Comment by evgenyrodionov** [comment]
What do you use?

**Comment by mcrawshaw** [comment]
Yes, imagine babel is complaining
``` @ multi react-hot-loader/patch webpack-dev-server/client?http://0.0.0.0:3000 webpack/hot/only-dev-server babel-polyfill ./src/client/index```

**Comment by evgenyrodionov** [comment]
Oh, I see, it all because [object spread operator](https://github.com/evgenyrodionov/redux-logger/blob/master/src/index.js#L25-L28).

What presets or plugins do you use?

**Comment by mcrawshaw** [comment]
```
presets: [
  ['es2015', { "modules": false }],
  'react'
],
```

**Comment by mcrawshaw** [comment]
Was working with 3.0.1.

**Comment by mcrawshaw** [comment]
Here is the full error:
```
ERROR in ./~/redux-logger/src/index.js
Module parse failed: /Users/markcrawshaw/Code/metamap/node_modules/redux-logger/src/index.js Unexpected token (26:4)
You may need an appropriate loader to handle this file type.
| function createLogger(options = {}) {
|   const loggerOptions = {
|     ...defaults,
|     ...options,
|   };
 @ ./src/universal/store/configureStore.dev.ts 4:0-44
 @ ./src/universal/store/index.ts
 @ ./src/client/app.tsx
 @ ./src/client/index.ts
 @ multi react-hot-loader/patch webpack-dev-server/client?http://0.0.0.0:3000 webpack/hot/only-dev-server babel-polyfill ./src/client/index
```

**Comment by evgenyrodionov** [comment]
3.0.1 deprecated, will fix asap

**Comment by evgenyrodionov** [comment]
3.0.3 released

**Comment by mcrawshaw** [comment]
Tested, it works, thanks.

**Comment by SamMatthewsIsACommonName** [comment]
@evgenyrodionov I'm getting a red box error like:
.../node_modules/redux-logger/dist/redux-logger.js 
Couldn't find preset "es2015" relative to directory "../node_modules/redux-logger"
do you think this is related? It's after updating to 3.0.3

**Comment by evgenyrodionov** [comment]
cc @thiamsantos

**Comment by thiamsantos** [comment]
@SamMatthewsIsACommonName weird problem. Which build process are you using?

**Comment by SamMatthewsIsACommonName** [comment]
Just building to run on the simulator (default debug I guess?) Sorry I'm not too familiar with build processes :/
3.0.1 is working. 
On android it has a little more detail with "the development server returned response error: 500"
all the error details are just empty strings, line 0 etc

**Comment by niranjan-b-prajapati** [comment]
I am also getting the error following is my package.json file:
```

{
	"name": "ReactNavigationApp",
	"version": "0.0.1",
	"private": true,
	"scripts": {
		"start": "node node_modules/react-native/local-cli/cli.js start",
		"test": "jest"
	},
	"dependencies": {
		"react": "16.0.0-alpha.6",
		"react-native": "0.44.0",
		"react-native-vector-icons": "^4.1.1",
		"react-navigation": "^1.0.0-beta.9",
		"react-redux": "^5.0.4",
		"redux": "^3.6.0",
		"redux-logger": "^3.0.3"
	},
	"devDependencies": {
		"babel-jest": "20.0.1",
		"babel-preset-react-native": "1.9.2",
		"jest": "20.0.1",
		"react-test-renderer": "16.0.0-alpha.6"
	},
	"jest": {
		"preset": "react-native"
	}
}

```

**Comment by evgenyrodionov** [comment]
@SamMatthewsIsACommonName @niranjan-b-prajapati you're using react-native? If yes, create `.babelrc` with following content:
```json
{
  "presets": ["babel-preset-react-native"]
}
```

**Comment by evgenyrodionov** [comment]
@thiamsantos we should bring back `.babelrc` from `package.json`, don't we?

**Comment by niranjan-b-prajapati** [comment]
@evgenyrodionov  i already have `.babelrc` file and it has following content:
```

{
  "presets": ["react-native"]
}

```

**Comment by evgenyrodionov** [comment]
@niranjan-b-prajapati interesting

**Comment by SamMatthewsIsACommonName** [comment]
I have the same but with flow as well
```
{
"presets": ["react-native", "flow"]
}
```

**Comment by niranjan-b-prajapati** [comment]
@evgenyrodionov sorry for asking silly question do i need to add  babel-preset-react-native with the react-native in presets ?

**Comment by evgenyrodionov** [comment]
@niranjan-b-prajapati @SamMatthewsIsACommonName please try `npm install --save redux-logger@beta`

**Comment by SamMatthewsIsACommonName** [comment]
Yeah that worked :)

**Comment by thiamsantos** [comment]
> @thiamsantos we should bring back .babelrc from package.json, don't we?

It probably not be the problem. Babel is only used on our build process, without influencing in the process of who imports the project. Right now our babel config is in a property at the package.json.

**Comment by niranjan-b-prajapati** [comment]
@evgenyrodionov thank you so much it worked, just had to do one minor change instead of 

`import logger from 'redux-logger'`

i had to change it to this:

`import { createLogger } from 'redux-logger'`

**Comment by niranjan-b-prajapati** [comment]
Sorry for asking such question but any one has any idea why the ios project of any latest react-native version when run on ios >10 keeps on logging following:

`nw_connection_get_connected_socket_block_invoke 3 Connection has no connected handler` 
the number keeps on increasing
