### ISSUE TITLE
Unexpected token - typo

### ISSUE THREAD

**Issue by raffjones** [evgenyrodionov/redux-logger#230]
This is causing an error:

    if (prevStateLevel) {
      if (colors.prevState) {
        logger[prevStateLevel](
          '%c prev state',
          `color: ${colors.prevState(prevState)}; font-weight: bold`,
          prevState,
        );
      } else logger[prevStateLevel]('prev state', prevState);
    }

You have a dangling comma after `prevState`

**Comment by evgenyrodionov** [comment]
Fixed in 3.0.5
