### ISSUE TITLE
UglifyJs Webpack build error when updated to the 3.0.4 version

### ISSUE THREAD

**Issue by avivshafir** [evgenyrodionov/redux-logger#231]
ERROR in app.js from UglifyJs
Unexpected token: punc (.) [./~/redux-logger/src/core.js:17,0][app.js:921,61]

Coming from a react+redux+typescript project built for production with webpack 2 
the project used 3.0.1 until now.
any ideas?

**Comment by thiamsantos** [comment]
@avivshafir could you please update the version to `3.0.6`

**Comment by avivshafir** [comment]
@thiamsantos it is now working. 
Thanks

**Comment by thiamsantos** [comment]
Good to hear. The problem was some mistakes that In made at #227.
