### ISSUE TITLE
`createLogger` doesn't seem to be exported correctly in latest build

### ISSUE THREAD

**Issue by ahumphreys87** [evgenyrodionov/redux-logger#233]
Just updated the 3.0.6 and getting errors in rollup saying:

`Error: 'createLogger' is not exported by node_modules/redux-logger/dist/redux-logger.js`

We can solve this using `namedExports` in the rollup-plugin-commonjs module but I think a better solution would be to readd js:next to package.json. If users are able to consume the ES2015 version it will allow apps using rollup to have tree shaking magic

**Comment by evgenyrodionov** [comment]
cc @thiamsantos

**Comment by thiamsantos** [comment]
@ahumphreys87 One thing that can be done is make rollup export an version that uses ES6 modules   and ES5 code in order [to prevent this problem](https://github.com/evgenyrodionov/redux-logger/commit/db841f3dd6bf739f697da59d522287a0a61b1850#commitcomment-22177335) too.

**Comment by ahumphreys87** [comment]
hmm, reading that - I dont think the lack of transpilation for modern bundlers is the concern of redux-logger.

If developers wish to consume the es2015 version then they are responsible for doing the transpilation (it can be configured to do so in the rollup-plugin-babel configuration).

The rollup resolver can also be configured to decide which properties to look for (js:next, browser, main etc)

**Comment by ahumphreys87** [comment]
or maybe even leave js:next in so that webpack doesnt automatically get it

**Comment by thiamsantos** [comment]
> If developers wish to consume the es2015 version then they are responsible for doing the transpilation (it can be configured to do so in the rollup-plugin-babel configuration).

Yes, I agree with you @ahumphreys87, but the majority of the people ignore the `node_modules` on transpilation. Also babel-loader [recommend to use in that way](https://github.com/babel/babel-loader#usage).

**Comment by ahumphreys87** [comment]
Yup, they recommend that by default. However allowing developers opt in to using the es2015 version is useful and if they manually opt in to using it then they should expect to have to do their own transpilation.

By default (`main`) its transpiled 👍  but using `js:next` it gives the option for tree-shaking, but opting into this means you need to do your own transpilation.

**Comment by ahumphreys87** [comment]
The main cause for this issue is that prior to upgrading to 3.0.6 I was able to use `import {createLogger} from 'redux-logger'` in rollup without issue. Now I receive the error.

**Comment by adipascu** [comment]
I fixed this issue by using [@types/redux-logger](https://www.npmjs.com/package/@types/redux-logger)

**Comment by mlynch** [comment]
Yea I can't get this to build in typescript with rollup with the latest. Tried the types to no avail. Getting the same error above.

**Comment by fredrikbergqvist** [comment]
> Yea I can't get this to build in typescript with rollup with the latest (3.0.6). Tried the types to no avail. Getting the same error above.

Same here:
```
"typescript": "3.3.3333"
"rollup": "1.6.0"
"@types/redux-logger": "3.0.6"
"redux-logger": "3.0.6"
```

**Comment by davthu** [comment]
can't get this to build with rollup using 3.0.7 either

**Comment by davthu** [comment]
We where able to build importing the default export:

```
import createLogger from "redux-logger";
const logger = createLogger({});
```

**Comment by chmelevskij** [comment]
For usage with rollup this worked for me
```javascript
import * as logger from 'redux-logger';

logger.__moduleExports.createLogger
```
