### ISSUE TITLE
Feature Request: Ability to customize title log

### ISSUE THREAD

**Issue by joyt** [evgenyrodionov/redux-logger#235]
It would be nice to be able to customize the displayed title log. For example, if you're adhering to Flux-Standard-Actions, being able to see the payload without have to expand is really useful.
For example:
```javascript
// User must handle color and formatting customization in this function.
function logTitle(log, getState, action, duration, timestamp) {
  log('action', action.type, `(in ${action.duration}ms)`, action.payload);
}
const loggerMiddleware = createLogger({logTitle, collapsed: true});
```

**Comment by evgenyrodionov** [comment]
`titleFormatter` option?

**Comment by joyt** [comment]
What would be the signature for `titleFormatter`? Would it let users log objects to the console? (as an object, not as `[object Object]`)?

**Comment by evgenyrodionov** [comment]
`titleFormatter` is [already exists](https://github.com/evgenyrodionov/redux-logger#titleformatter--action-object-time-string-took-number--title).

**Comment by joyt** [comment]
Sorry, I didn't notice `titleFormatter` at first! However since its return type is a string, I'm not sure how to make it pretty-log a object. I guess I could use `JSON.stringify(payload)`, but that would get unwieldy with nested objects.

**Comment by evgenyrodionov** [comment]
Ah, I see. Probably, you can disable prev state and next state and use non-collapsed output.

```js
const logger = createLogger({
  level: {
    prevState: false,
    action: 'log',
    nextState: false
  }
});
```

**Comment by joyt** [comment]
Hmm, but then I don't get to see `prevState` and `nextState` at all, and I still have to expand the `payload` of the `action` object to see the contents of it...

What if `titleFormatter` could return an array in addition to a string, and if the return type is an array, you call `console.log` with the array as the arguments?

**Comment by evgenyrodionov** [comment]
No, it's too complicated

**Comment by joyt** [comment]
Ok, how about adding a `payload: true` option to the config that would add `action.payload` to the title?

**Comment by evgenyrodionov** [comment]
It's too complicated too and needs to less than 1% of users. Feel free to fork and use your own version.
