### ISSUE TITLE
use babel-preset-env over babel-preset-es2015

### ISSUE THREAD

**Issue by graingert** [evgenyrodionov/redux-logger#238]

**Comment by thiamsantos** [comment]
@graingert why do you think that change should be made?

**Comment by graingert** [comment]
@thiamsantos babel-preset-env is the recommended preset: https://babeljs.io/#es2015-and-beyond

**Comment by evgenyrodionov** [comment]
Feel free to create PR

**Comment by graingert** [comment]
@evgenyrodionov can you re-open this for the PR?

**Comment by evgenyrodionov** [comment]
@graingert ok but for what?

**Comment by graingert** [comment]
So I can link the PR to the issue...?

**Comment by grushetsky** [comment]
@graingert, FYI, it's possible to leave a link to the closed issue in a pull request.
