### ISSUE TITLE
Interferes with redux-promise-middleware

### ISSUE THREAD

**Issue by nicnilov** [evgenyrodionov/redux-logger#242]
When I have `logger` middleware before `redux-promise-middleware` when applying, like this:

    applyMiddleware([logger, thunk, promiseMiddleware()])

it leads to promiseMiddleware not sending the correct `_PENDING` action. E.g. when I have a `LOG_IN` action, promiseMiddleware is expected to send a `LOG_IN_PENDING` and a `LOG_IN_FULFILLED` actions one after another. Instead it sends a `LOG_IN` and a `LOG_IN_FULFILLED` actions. When the logger is placed at the end of the middleware list, this doesn't happen. The action type is generated by promiseMiddleware on the fly and logger seems to interfere with that.

**Comment by evgenyrodionov** [comment]
Fill issue to `redux-promise-middleware`, `redux-logger` just logs `dispatch()` events
