### ISSUE TITLE
While using redux, uncaught TypeError: undefined is not a function 

### ISSUE THREAD

**Issue by Kilims** [evgenyrodionov/redux-logger#248]
redux-logger version :1.0.0/3.0.0

code snippets:

```
import {appliMiddleware, createStore} from 'redux';
import logger from 'redux-logger';

const middleware = appliMiddleware(logger);
const store = createStore(reducers, middleware);
```

After adding this redux-logger middleware , it shows the error
`Uncaught TypeError: undefined is not a function `

the chrome version is 37.0

I hitted this error before , for the chrome 37 not support some ES6 functions, dont know if this 
redux-logger error is relative or not.

Could u help ?

**Comment by evgenyrodionov** [comment]
Latest Chrome version is 59.0.3071.115.
Latest redux-logger version is 3.0.6.

Also you misspelled `applyMiddleware` as `appliMiddleware`.
