### ISSUE TITLE
PrevState and NextState is not shown on console

### ISSUE THREAD

**Issue by luqmanrom** [evgenyrodionov/redux-logger#251]
My logger stop showing prevState, action and next state. I can't collapse the text either. Is there any options that I should include in `createLogger`?

![screen shot 2017-08-13 at 6 30 20 pm](https://user-images.githubusercontent.com/6434819/29248876-b0164dbe-8055-11e7-96c6-1509ab0515e2.png)

**Comment by evgenyrodionov** [comment]
It's Chrome feature, see toggle right after Filter

**Comment by luqmanrom** [comment]
@evgenyrodionov Great. Thanks very much

**Comment by abranhe** [comment]
My case only needed to select the message tab, for those who are visual:

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/21347264/64058946-89d1ef00-cb80-11e9-972d-b41d6fcde785.gif)

Hope it helps!
