### ISSUE TITLE
 'artifactory' is not in the npm registry.

### ISSUE THREAD

**Issue by frankofamerica** [evgenyrodionov/redux-logger#260]
I am receiving this when running npm i from my project.

'artifactory' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)

**Comment by evgenyrodionov** [comment]
How it related to redux-logger?

**Comment by thiamsantos** [comment]
@frankofamerica Why do you think that this problem has anything to do with `redux-logger`?

[`artifactory` is not a dependency of this project](https://github.com/evgenyrodionov/redux-logger/blob/master/package.json#L60,L86).
