### ISSUE TITLE
I get issue when using logger after run npm build. How to solve?

### ISSUE THREAD

**Issue by permadiwibisono** [evgenyrodionov/redux-logger#266]
In development or `npm start` it still work properly with logger middleware. But I get issue after `npm run build`. The error message : `f[(f.length - 1)] is undefined`. And when I'm not using logger middleware in `npm run build`. The page working properly. Here is my code:

```javascript
import { createStore, applyMiddleware } from 'redux';
import thunk from 'redux-thunk';
import logger from 'redux-logger';
import rootReducer from '../reducers'

import { loadingBarMiddleware } from 'react-redux-loading-bar'
import promiseMiddleware from 'redux-promise-middleware';

const store = createStore(rootReducer, applyMiddleware(thunk, promiseMiddleware(), loadingBarMiddleware(), logger))

export default store;
```

**Comment by grushetsky** [comment]
@permadiwibisono, why have you concluded that this problem has something to do with `redux-logger` package? The example provides no indication of that. Closing the issue for now.
