### ISSUE TITLE
Redux as peerDependency?

### ISSUE THREAD

**Issue by jherencia** [evgenyrodionov/redux-logger#268]
Sorry about the question, and congrats for the amazing work.

I'm trying to figure out what are the current dependencies of this library but I see there is no mention in the package.json about this, but I assume that it could be some incompatibilities with redux 4.x.

Why is not any peerDependency mention to redux in package.json?

**Comment by evgenyrodionov** [comment]
I don't see any breaking changes, so redux-logger will be work nicely.
