### ISSUE TITLE
How to remove all @@redux-form state change information from console

### ISSUE THREAD

**Issue by zymr-keshav** [evgenyrodionov/redux-logger#269]
I am using redux-form and dues to this, logger logs too many state changes information on each action such as blur focus and calling everytime that's why my console get full and unable to watch any other user state change.

in console there is panel for each action such as 

```
@@redux-form/FOCUS

@@redux-form/CHANGE

@@redux-form/UPDATE_SYNC_ERRORS
```

so my query is 

How to customize logger in a way to take out these @@redux-form state change from log display?

**Comment by evgenyrodionov** [comment]
Option [predicate](https://github.com/evgenyrodionov/redux-logger#predicate--getstate-function-action-object--boolean)

```js
const logger = createLogger({
  predicate: ({ type }) => !type.includes('@@redux-form')
});
```

**Comment by zymr-keshav** [comment]
gives error 
`Cannot read property 'includes' of undefined` 

using es6 and redux-logger v 3.0.6

**Comment by grushetsky** [comment]
@zymr-keshav, the original example missed the first argument for `predicate` function. Here's a fix for it:
```javascript
const logger = createLogger({
  predicate: (getState, { type }) => !type.includes('@@redux-form')
});
```
 actions must have that is because `Array.prototype.includes` is the part of ES7 (ES2016) and not ES6 (ES2015). You can use the appropriate polyfill to fix the problem.
