### ISSUE TITLE
Using redux-logger in production.

### ISSUE THREAD

**Issue by Tomekmularczyk** [evgenyrodionov/redux-logger#270]
It's a question rather than an issue. 
I really like this package because of its simplicity, but I need to somehow track what's happening inside app when debugging production errors. So my question is "is it safe to let redux-logger in production or can I somehow make it safe"?
I have read that it's OK to use [redux-devtools-extension](https://medium.com/@zalmoxis/using-redux-devtools-in-production-4c5b56c5600f) in production.

**Comment by grushetsky** [comment]
We tried it out in production mode and it worked well! But you should take into account the target platform and profile your app both with and without `redux-logger`.
