### ISSUE TITLE
logger usage in Xcode React Native —— log end ——

### ISSUE THREAD

**Issue by ChristophRob** [evgenyrodionov/redux-logger#277]
Hi,

as i am using react-native its not possible to use a browser console with my Iphone-Simulator. So i use the redux-logger in xcode Debugger Console with the following setting:

`const loggerMiddleware = createLogger({
  level: {
    prevState: false,
    action: false,
    nextState: 'log',
    error: 'log',
  }
})`

This works fine and is quite helping. The only thing that annoys me, is the "—— log end ——" at the end of every dispatch. Is it anyhow possible to prevent that?

Thanks!

**Comment by ChristophRob** [comment]
Thinks its useless to use redux-logger without a browser console. I just use the Redux Middleware example: https://redux.js.org/docs/advanced/Middleware.html

**Comment by xavierartot** [comment]
You can use Reactotron
