### ISSUE TITLE
Redux logger 3.0.6 requires Object.assign

### ISSUE THREAD

**Issue by adipascu** [evgenyrodionov/redux-logger#278]
If the browser does not support Object.assign then `undefined is not a function` is thrown.
This is a breaking change from the previous version: 3.0.1 .

**Comment by RileyEllis** [comment]
I am seeing this too, our entire application breaks on IE11 because redux-logger has a non-polyfilled Object.assign

**Comment by tswaters** [comment]
Is it the responsibility of a library or the application to perform a polyfill?

If the library does it, it'll be embedded in that library code, increasing it's size... if any other libraries require the same thing and also polyfill, they'll need to embed the same thing - increasing file size further, and worse, performing the polyfill multiple times.

It's typically recommended to run a polyfill once.  Libraries have no way of knowing if any other library, or the application code itself has performed the polyfill.  I'd typically stray away from libraries modifying global state so they can run in isolation.... this is the job of the application.

Sounds like you need to `import 'babel-polyfil'`.

That said, I'd argue that this was in fact a breaking change.... in the readme there should be notes about features that are requires in a given js environment for it to run properly... so consumers are at least aware that they need to include polyfills.

**Comment by evgenyrodionov** [comment]
@tswaters that’s right. Will update soon.

**Comment by adipascu** [comment]
I switched to [small-redux-logger](https://www.npmjs.com/package/small-redux-logger) as a simpler alternative that runs on old browsers.
