### ISSUE TITLE
Latest Chrome broke logging info?

### ISSUE THREAD

**Issue by cuong-nguyen** [evgenyrodionov/redux-logger#280]
Hi guys, here is what gets logged on my console

<img width="981" alt="screen shot 2018-01-15 at 5 13 28 pm" src="https://user-images.githubusercontent.com/5061591/34935146-d498255e-fa17-11e7-870a-ce93a4082fe9.png">

OS: Mac 10.12.6
Browser: Chrome
Version 63.0.3239.132

It seems to work just a few days ago. Also working fine on latest Firefox.
Is this just me?

**Comment by evgenyrodionov** [comment]
Check Log level in console

**Comment by cuong-nguyen** [comment]
Wow, quick response. Unfortunately, I tried to turn on all the log level (Verbose, Info, Warnings, Errors) and it still does not work.

**Comment by evgenyrodionov** [comment]
Hm, will check in 2-3 hours. Can you show your settings?

**Comment by cuong-nguyen** [comment]
I also tried to remove and install again, then clear cache,... but no luck.
What do you mean by **settings**, code settings to setup the logger?

**Comment by evgenyrodionov** [comment]
Yep

**Comment by cuong-nguyen** [comment]
Here you go, I tried to use ES6 syntax to import `createLogger` and it's still the same
```
const middlewares = [];

if (Constant.ENABLE_LOGGER === true) {
  const {createLogger} = require('redux-logger');
  const logger = createLogger({
    diff: true
  });

  middlewares.push(logger);
}
```

**Comment by evgenyrodionov** [comment]
Can you make demo on https://codesandbox.io?

**Comment by cuong-nguyen** [comment]
Sorry, silly mistake. Somehow I set the filter to hide all info coming from my bundle. Right click on console log window -> Filter -> Unhide fix the issue.

You can close this issue now.
