### ISSUE TITLE
Wrong data logged.

### ISSUE THREAD

**Issue by Tomekmularczyk** [evgenyrodionov/redux-logger#287]
I'm not sure is it a bug, but logger should print what is coming into the reducer not what's coming out of it (?)... anyway, I would like someone to explain me this situation:

```javascript
  //  middleware config
  const middleware = [thunk, epicMiddleware];
  const logger = createLogger({ collapsed: true, diff: true });
  if (env.isDevelopment) middleware.push(logger); // tried with unshift too
```

Here are whats coming to reducer on `FETCH_PRICING_PLANS_SUCCESS` (notice lack of `name` field):
![image](https://user-images.githubusercontent.com/12544704/35498904-999087f8-04d0-11e8-8ed2-b1bfde26439d.png)

And here is what logger prints (notice `name` field):
![image](https://user-images.githubusercontent.com/12544704/35498966-e6d72058-04d0-11e8-90dc-084a5b04ac5b.png)

And I bet this is because of that part of the code, where I use lodash `defaultsDeep` to append required properties that were not present in API response.

But my questions is, is it desired behavior or I'm doing something wrong? I think this happens because the object is being mutated and logger prints mutated object. But in this case, I don't care about backend response object being mutated and I would like to know what's coming with an action to the reducer.

I'm, just curious what's your thoughts.

P.S I think this could be related to #193 because logging happens after action hit the reducer.

**Comment by evgenyrodionov** [comment]
Can you make demo on codesandbox.io?

**Comment by Tomekmularczyk** [comment]
@evgenyrodionov Yes. I will prepare demo later this day.

**Comment by Tomekmularczyk** [comment]
@evgenyrodionov [here's the example](https://codesandbox.io/s/kopw7l9x2v). 

FETCH_DATA_SUCCESS action `payload` is different than what is logged in a console.

**Comment by MichelSimonot** [comment]
The reason this is happening is because the reducer is mutating the action, which it shouldn't be doing. It is an anti-pattern for a reducer to mutate an action.

References: [Redux docs](https://redux.js.org/docs/basics/Reducers.html#handling-actions) / [Redux co-author](https://github.com/coodoo/react-redux-isomorphic-example/issues/9#issue-98292098)

**Comment by Tomekmularczyk** [comment]
fair enough

**Comment by evgenyrodionov** [comment]
Well
