### ISSUE TITLE
Not collapsed when using together with loglevel

### ISSUE THREAD

**Issue by jonaskello** [evgenyrodionov/redux-logger#288]
I tried with [loglevel](https://github.com/pimterry/loglevel) as custom logger like this:

```
import * as log from "loglevel";
import * as createLogger from "redux-logger";
const logger = createLogger({ collapsed: true, logger: log });
```

It works but the entries are not collapsed anymore. Instead they appear like this in the console:

```
action @ 15:38:53.762 @@router/LOCATION_CHANGE
core.js:111  prev state {routing: {…}, oidc: {…}, ui: {…}, settings: {…}, query: {…}, …}
core.js:115  action {type: "@@router/LOCATION_CHANGE", payload: {…}}
core.js:123  next state {routing: {…}, oidc: {…}, ui: {…}, settings: {…}, query: {…}, …}
core.js:133 —— log end ——
```

Anyone has a pointer how to configure it so it still produces collapsed entries?

**Comment by MichelSimonot** [comment]
It doesn't look like `loglevel` supports `console.group` (https://github.com/pimterry/loglevel/issues/26), which I _think_ would cause what you're seeing.

**Comment by jonaskello** [comment]
I think you are right about that, it probably has to be fixed in logevel. Closing this as the problem is not in this repo.
