### ISSUE TITLE
expose an action to switch logging off/on

### ISSUE THREAD

**Issue by jonathanadler** [evgenyrodionov/redux-logger#294]
I wasn't sure this kind of option exists.
I know this would help me a lot while developing.

I'll give a use case:
At work we use this library, which is very helpful, and we conditionally add it to our middleware depending on the environment (dev only basically).
The thing is that most of the time, I don't need it, and I would love to have a way to toggle it off or on.
What I do now is remove the line of code, adding the middleware, completely, then forgetting about it, and committing it to the master branch 😕 

What do you guys think?

**Comment by Rycochet** [comment]
You can always do this yourself with a global variable, and the `predicate` option returning that global - then an action to toggle it ;-)

Just as an option - why not do something on `localStorage`, and then you can toggle it and a simple reload will change it - `localStorage["enableLogging"] = true`, then have `if (localStorage["enableLogging"]) {...createLogger...}`

... And just about to add that to mine as it makes sense!

**Comment by jonathanadler** [comment]
That's a great idea @Rycochet.

I thought that if this feature request would be more popular, it would have been nice to have this predicate solution a part of the library, without needing to write it in every project.

However, since I see there's no such demand, your suggestion is more than sufficient 👍
