### ISSUE TITLE
redux-logger can't print any information about state and action

### ISSUE THREAD

**Issue by Feel-Joy** [evgenyrodionov/redux-logger#296]
Hi, I'm learning redux for several days, and I tried to use redux-logger in my todoList demo, but seems it doesn't work, it just print prev state, action, next state... but nothing about the state and action,  [this](https://codesandbox.io/s/3vq81545v1) is my demo on codesandbox, can someone help me to resolve this problem?

**Comment by MichelSimonot** [comment]
> it just print prev state, action, next state... but nothing about the state and action

Can you better explain what you're seeing? That sandbox seems to be printing the action logs as expected.

![screen shot 2018-05-22 at 9 24 30 am](https://user-images.githubusercontent.com/1817346/40365174-003c3720-5da2-11e8-8344-9f96618989d4.png)

**Comment by Feel-Joy** [comment]
Below is what I saw in codesandbox, but I tried download this project and run it at local env, it was worked well, it seems something wrong with redux-logger at codesandbox.
![2018-05-25 4 51 58](https://user-images.githubusercontent.com/25546299/40538231-b6aa7320-6043-11e8-8681-28deabe601d1.png)

**Comment by MichelSimonot** [comment]
It doesn't look like a problem with redux-logger. That console is CodeSandbox's console, not the browser console. It seems that the CodeSandbox console just doesn't support arguments after styling.

![screen shot 2018-05-25 at 7 51 34 am](https://user-images.githubusercontent.com/1817346/40543012-8b1a8068-5ff0-11e8-9c7a-0713b8e511ae.png)


If you use the browser's console, you should see everything as expected.

**Comment by Feel-Joy** [comment]
@MichelSimonot Yes, redux-logger works great with browser's console, very thanks for your help!
