### ISSUE TITLE
[ts] Cannot find name 'reducer'

### ISSUE THREAD

**Issue by dfdumaresq** [evgenyrodionov/redux-logger#301]
I'm unable to get this running with the getting-started example.

<img width="916" alt="reducer-error" src="https://user-images.githubusercontent.com/20051/41066375-7a68949e-6996-11e8-8ccb-f39c693b09ce.png">

The issue is that 'reducer' is causing a TS error with Cannot find name 'reducer'.

My environment is MacOS, ASP Net.Core. React, Redux, and I had to install
```npm install --save-dev @types/redux-logger```

**Comment by evgenyrodionov** [comment]
You need to create redux reducer. 

https://redux.js.org/api-reference/createstore
