### ISSUE TITLE
Redux logger shows undefined action type with action as function body

### ISSUE THREAD

**Issue by theapache64** [evgenyrodionov/redux-logger#302]
I am new in the world of react and redux. I am getting below output in my console.

![image](https://user-images.githubusercontent.com/9678279/41303287-7681a624-6e8a-11e8-8e5a-4dcf2cf0ac64.png)

Is this normal to have action type with `undefined` and action body as `function body` ? or am i missing something ? 

Here's my store

```
const store = createStore(
    rootReducer,
    initialState,
    compose(applyMiddleware(logger,thunk, axiosMiddleware.default(client))),
);

export default store;
```

**Comment by MichelSimonot** [comment]
logger must be the last middleware in chain, otherwise it will log thunk and promise, not actual actions (#20).

**Comment by theapache64** [comment]
Ok

**Comment by SeanFelipe** [comment]
@MichelSimonot you just saved my life dude. !!!

**Comment by p-christ** [comment]
thanks a lot @MichelSimonot  !!!

**Comment by avinash-dewangan** [comment]
@MichelSimonot Thanks its working fine

**Comment by iamgabrielsoft** [comment]
Comming back to this issue also saved me,  thanks to @michaelsimonot. 

Making the logger middleware the last

**Comment by iamgabrielsoft** [comment]
Comming back to this git issue after 2 years also saved me, thanks to @MichelSimonot 

Cheers guys....

**Comment by MounirEl-Abbas** [comment]
> logger must be the last middleware in chain, otherwise it will log thunk and promise, not actual actions (#20).

Man, I spent so much time, thank you so much man, finaaalllyyy
